title: Olamide Olayinka
logo: assets/img/headshot.png
description: Data Science | Machine Learning | SQL & Python | Risk Analytics | Data Visualization
show_downloads: false
theme: jekyll-theme-minimal
